apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: Store
metadata:
  name: bionic-store
spec:
  sources:
  - image: cloudfoundry/cnb:bionic
---
apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: Stack
metadata:
  name: bionic-stack
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "cloudfoundry/build:0.0.10-base-cnb"
  runImage:
    image: "cloudfoundry/run:0.0.12-base-cnb"
---
apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: CustomBuilder
metadata:
  name: my-custom-builder
spec:
  tag: jasonmorgan/custom-builder
  serviceAccount: jason-hub
  stack: bionic-stack
  store: bionic-store
  order:
  - group:
    - id: org.cloudfoundry.openjdk
    - id: org.cloudfoundry.buildsystem
      optional: true
    - id: org.cloudfoundry.jvmapplication
    - id: org.cloudfoundry.tomcat                       
      optional: true
    - id: org.cloudfoundry.springboot                   
      optional: true
    - id: org.cloudfoundry.distzip                      
      optional: true
    - id: org.cloudfoundry.procfile                     
      optional: true
    - id: org.cloudfoundry.azureapplicationinsights     
      optional: true
    - id: org.cloudfoundry.debug                        
      optional: true
    - id: org.cloudfoundry.googlestackdriver            
      optional: true
    - id: org.cloudfoundry.jdbc                         
      optional: true
    - id: org.cloudfoundry.jmx                          
      optional: true
    - id: org.cloudfoundry.springautoreconfiguration    
      optional: true
  - group:
    - id: org.cloudfoundry.go
    

