apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: Store
metadata:
  name: bionic-store
spec:
  sources:
  - image: gcr.io/paketo-buildpacks/builder:base
---
apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: Stack
metadata:
  name: bionic-stack
spec:
  id: "org.cloudfoundry.stacks.cflinuxfs3"
  buildImage:
    image: "paketobuildpacks/build:0.0.19-base-cnb"
  runImage:
    image: "paketobuildpacks/run:0.0.19-base-cnb"
---
apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: CustomBuilder
metadata:
  name: 59s-custom-builder
spec:
  tag: jasonmorgan/custom-builder
  serviceAccount: jason-hub
  stack: bionic-stack
  store: bionic-store
  order:
  - group:
    - id:  paketo-buildpacks/go
  - group:
    - id:  paketo-buildpacks/java
  - group:
    -id: paketo-buildpacks/nodejs
  - group:
    -id: paketo-buildpacks/dotnet-core
  - group:
    -id: paketo-buildpacks/php
  - group:
    -id: paketo-buildpacks/httpd
  - group:
    -id: paketo-buildpacks/nginx
  - group:
    -id: paketo-buildpacks/procfile

