apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: Store
metadata:
  name: bionic-store
spec:
  sources:
  - image: cloudfoundry/cnb:bionic
---
apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: Stack
metadata:
  name: bionic-stack
spec:
  id: "org.cloudfoundry.stacks.cflinuxfs3"
  buildImage:
    image: "paketobuildpacks/build:0.0.63-full-cnb-cf"
  runImage:
    image: "paketobuildpacks/run:0.0.64-full-cnb-cf"
---
apiVersion: experimental.kpack.pivotal.io/v1alpha1
kind: CustomBuilder
metadata:
  name: my-custom-builder
spec:
  tag: jasonmorgan/custom-builder
  serviceAccount: jason-hub
  stack: bionic-stack
  store: bionic-store
  order:
  - group:
    - id: paketo-buildpacks/java
  - group:
    - id:  paketo-buildpacks/go
    

