---
apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: golang-redis
spec:
  tag: index.docker.io/jasonmorgan/golang-redis
  serviceAccount: jason-hub
  cacheSize: "1.5Gi"
  builder:
    name: my-custom-builder
    kind: CustomBuilder
  source:
    git:
      url: https://github.com/techgnosis/pas-golang-redis.git
      revision: master
---
apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: golang-mysql
spec:
  tag: index.docker.io/jasonmorgan/golang-mysql
  serviceAccount: jason-hub
  cacheSize: "1.5Gi"
  builder:
    name: my-custom-builder
    kind: CustomBuilder
  source:
    git:
      url: https://github.com/techgnosis/pas-golang-mysql.git
      revision: master