---
apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: golang-hello-world
spec:
  tag: index.docker.io/jasonmorgan/golang-redis
  serviceAccount: jason-hub
  cacheSize: "1.5Gi"
  builder:
    name: 59s-custom-builder
    kind: CustomBuilder
  source:
    git:
      url: https://github.com/techgnosis/pas-golang-redis.git
      revision: master
---
apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: spring-petclinic
spec:
  tag: index.docker.io/jasonmorgan/spring-petclinic
  serviceAccount: jason-hub
  cacheSize: "1.5Gi"
  builder:
    name: 59s-custom-builder
    kind: CustomBuilder
  source:
    git:
      url: https://github.com/jasonmorgan/spring-petclinic.git
      revision: master