apiVersion: v1
kind: Secret
metadata:
  name: <secretName>
  annotations:
    build.pivotal.io/docker: <registry-prefix>
type: kubernetes.io/basic-auth
stringData:
  username: <username>
  password: <password>
